#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_SIDNEY      0
#define MUGSHOT_PHOEBE      1
#define MUGSHOT_GLACIA      2
#define MUGSHOT_DRAKE       3
#define MUGSHOT_CHAMPION    4
#define MUGSHOT_ROXANNE     5
#define MUGSHOT_BRAWLY      6
#define MUGSHOT_WATTSON     7
#define MUGSHOT_FLANNERY    8
#define MUGSHOT_NORMAN      9
#define MUGSHOT_NED         10
#define MUGSHOT_TATELIZA    11
#define MUGSHOT_BENDER      12

#define MUGSHOTS_COUNT      13

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H